/**
 * TypeScript client SDK for Clocky runtime: spawn the
 * `clocky-jsonrpc-agent` runtime as a subprocess and drive agent turns over
 * stdio JSON-RPC. `Clocky` is the high-level run API;
 * `HarnessClient` is the lower-level protocol client. A pure library — it
 * registers nothing on a Cordis context; the runtime process it spawns is a
 * complete harness configured by its own `cordis.yml`.
 *
 * @module @clocky/clocky-sdk-client
 */

export { Clocky, HarnessTeam } from './api.ts'
export type { RunOptions, TeamCreateOptions } from './api.ts'
export {
  HarnessClient,
  parseActivationStatusNotification,
  RequestTimeoutError,
  SdkProtocolError,
  TransportClosedError,
} from './client.ts'
export type { NotificationSubscription } from './client.ts'
export { JsonRpcResponseError } from '@clocky/clocky-sdk-protocol'
export type {
  ContentBlock,
  ClockyOptions,
  HarnessClientOptions,
  HarnessNotification,
  NotificationFilter,
  RunResult,
} from './types.ts'
export type {
  ActivationDisposeParams,
  ActivationInterruptParams,
  ActivationLinkEnrollParams,
  ActivationLinkEnrollResult,
  ActivationOpenParams,
  ActivationStatusNotification,
  ActivationStatusParams,
  SdkActivationInterruptCause,
  SdkActivationSeed,
  SdkActivationState,
  SdkActivationStatus,
  SdkActivationTarget,
  SdkTeamLinkBinding,
  SdkTeamLinkEnrollment,
  TeamCancelParams,
  TeamCancelResult,
  TeamArchiveParams,
  TeamArchiveResult,
  TeamCreateParams,
  TeamCreateResult,
  TeamWaitFinalParams,
  TeamWaitFinalResult,
  TeamListParams,
  TeamListResult,
  TeamGetParams,
  TeamGetResult,
  TeamGoalUpdateParams,
  TeamGoalUpdateResult,
  TeamGoalTransitionParams,
  TeamGoalTransitionResult,
  TeamQuiescenceParams,
  TeamQuiescenceResult,
  TeamMetricsParams,
  TeamMetricsResult,
  TeamAuditReadParams,
  TeamAuditReadResult,
  TeamArtifactReadParams,
  TeamArtifactReadResult,
  TeamArtifactListParams,
  TeamArtifactListResult,
  TeamMemberListParams,
  TeamMemberListResult,
  TeamMemberInviteParams,
  TeamMemberInviteResult,
  TeamMemberActivateParams,
  TeamMemberActivateResult,
  TeamMemberRemoveParams,
  TeamMemberRemoveResult,
  TeamMemberInterruptParams,
  TeamMemberInterruptResult,
  TeamChannelCatalogParams,
  TeamChannelCatalogResult,
  TeamChannelSummarizeParams,
  TeamChannelSummarizeResult,
  TeamChannelListParams,
  TeamChannelListResult,
  TeamChannelAdmissionParams,
  TeamChannelAdmissionResult,
  TeamChannelOpenParams,
  TeamChannelOpenResult,
  TeamChannelInputParams,
  TeamChannelInputContent,
  TeamChannelAttachmentParams,
  TeamChannelAttachmentResult,
  TeamChannelPostParams,
  TeamChannelPostResult,
  TeamChannelReadParams,
  TeamChannelReadResult,
  TeamChannelCloseParams,
  TeamChannelCloseResult,
  TeamChannelWatchParams,
  TeamChannelWatchResult,
  TeamTaskCreateParams,
  TeamTaskCreateResult,
  TeamTaskGetParams,
  TeamTaskGetResult,
  TeamTaskListParams,
  TeamTaskListResult,
  TeamWorkflowPlanListParams,
  TeamWorkflowPlanListResult,
  TeamTaskUpdateParams,
  TeamTaskUpdateResult,
  TeamTaskCancelParams,
  TeamTaskCancelResult,
  TeamTaskDeleteParams,
  TeamTaskDeleteResult,
  TeamTaskReviewParams,
  TeamTaskReviewResult,
  TeamTaskWatchParams,
  TeamTaskWatchResult,
} from '@clocky/clocky-sdk-protocol'

export type { TeamInboxRespondParams } from '@clocky/clocky-sdk-protocol'
