/** Typed errors raised by Team service-definition registries and providers. @module @clocky/clocky-team/error */

import type { JsonObject } from './types.ts'

/** Machine-routable Team service-definition error code. */
export type TeamErrorCode =
  | 'TEAM_DELEGATION_BUSY'
  | 'TEAM_DELEGATION_INVALID'
  | 'TEAM_DELEGATION_WORKSPACE_UNAVAILABLE'
  | 'TEAM_DELEGATION_CHILD_MISSING'
  | 'TEAM_DELEGATION_CHANNEL_UNAVAILABLE'
  | 'TEAM_ADAPTER_DUPLICATE'
  | 'TEAM_ADAPTER_NOT_FOUND'
  | 'TEAM_POLICY_DUPLICATE'
  | 'TEAM_NOT_FOUND'
  | 'TEAM_DISCOVERY_CURSOR_EXPIRED'
  | 'TEAM_CURSOR_CONFLICT'
  | 'TEAM_POLICY_DENIED'
  | 'TEAM_PARTICIPANT_NOT_FOUND'
  | 'TEAM_ACTIVATION_NOT_FOUND'
  | 'TEAM_ACTIVATION_FENCE_UNAVAILABLE'
  | 'TEAM_ACTIVATION_FENCE_FAILED'
  | 'TEAM_ACTIVATION_RECOVERY_UNSUPPORTED'
  | 'TEAM_ACTIVATION_RECOVERY_CONFLICT'
  | 'TEAM_ACTOR_PROOF_INVALID'
  | 'TEAM_HUMAN_ACTOR_NOT_FOUND'
  | 'TEAM_HUMAN_ACTOR_AMBIGUOUS'
  | 'TEAM_HUMAN_ACTOR_FORBIDDEN'
  | 'TEAM_HUMAN_ACTOR_PROOF_SOURCE_DUPLICATE'
  | 'TEAM_HUMAN_ACTOR_PROOF_SOURCE_INVALID'
  | 'TEAM_SYSTEM_ACTIVATION_PROOF_SOURCE_DUPLICATE'
  | 'TEAM_SYSTEM_ACTIVATION_PROOF_SOURCE_INVALID'
  | 'TEAM_SYSTEM_HUMAN_ACTION_PROOF_SOURCE_DUPLICATE'
  | 'TEAM_SYSTEM_HUMAN_ACTION_PROOF_SOURCE_INVALID'
  | 'TEAM_SYSTEM_TASK_LEASE_PROOF_SOURCE_DUPLICATE'
  | 'TEAM_SYSTEM_TASK_LEASE_PROOF_SOURCE_INVALID'
  | 'TEAM_SYSTEM_WORKFLOW_PROOF_SOURCE_DUPLICATE'
  | 'TEAM_SYSTEM_WORKFLOW_PROOF_SOURCE_INVALID'
  | 'TEAM_SYSTEM_TASK_CONTROL_PROOF_SOURCE_DUPLICATE'
  | 'TEAM_SYSTEM_TASK_CONTROL_PROOF_SOURCE_INVALID'
  | 'TEAM_SYSTEM_ROOT_CREATION_PROOF_SOURCE_DUPLICATE'
  | 'TEAM_SYSTEM_ROOT_CREATION_PROOF_SOURCE_INVALID'
  | 'TEAM_SYSTEM_CHILD_CREATION_PROOF_SOURCE_DUPLICATE'
  | 'TEAM_SYSTEM_CHILD_CREATION_PROOF_SOURCE_INVALID'
  | 'TEAM_SYSTEM_CHANNEL_SUMMARY_PROOF_SOURCE_DUPLICATE'
  | 'TEAM_SYSTEM_CHANNEL_SUMMARY_PROOF_SOURCE_INVALID'
  | 'TEAM_SYSTEM_CHANNEL_LIFECYCLE_PROOF_SOURCE_DUPLICATE'
  | 'TEAM_SYSTEM_CHANNEL_LIFECYCLE_PROOF_SOURCE_INVALID'
  | 'TEAM_SYSTEM_WORKSPACE_ALLOCATION_PROOF_SOURCE_DUPLICATE'
  | 'TEAM_SYSTEM_WORKSPACE_ALLOCATION_PROOF_SOURCE_INVALID'
  | 'TEAM_SYSTEM_ARCHIVE_PROOF_SOURCE_DUPLICATE'
  | 'TEAM_SYSTEM_ARCHIVE_PROOF_SOURCE_INVALID'
  | 'TEAM_SYSTEM_TOPOLOGY_PROOF_SOURCE_DUPLICATE'
  | 'TEAM_SYSTEM_TOPOLOGY_PROOF_SOURCE_INVALID'
  | 'TEAM_SYSTEM_SCHEDULER_CHANNEL_PROOF_SOURCE_DUPLICATE'
  | 'TEAM_SYSTEM_SCHEDULER_CHANNEL_PROOF_SOURCE_INVALID'
  | 'TEAM_SYSTEM_CANCELLATION_CLEANUP_PROOF_SOURCE_DUPLICATE'
  | 'TEAM_SYSTEM_CANCELLATION_CLEANUP_PROOF_SOURCE_INVALID'
  | 'TEAM_SYSTEM_FINALIZATION_CLEANUP_PROOF_SOURCE_DUPLICATE'
  | 'TEAM_SYSTEM_FINALIZATION_CLEANUP_PROOF_SOURCE_INVALID'
  | 'TEAM_SYSTEM_FINAL_RECEIPT_PROOF_SOURCE_DUPLICATE'
  | 'TEAM_SYSTEM_FINAL_RECEIPT_PROOF_SOURCE_INVALID'
  | 'TEAM_SYSTEM_ENVELOPE_POST_PROOF_SOURCE_DUPLICATE'
  | 'TEAM_SYSTEM_ENVELOPE_POST_PROOF_SOURCE_INVALID'
  | 'TEAM_SYSTEM_CLOSURE_PROOF_SOURCE_DUPLICATE'
  | 'TEAM_SYSTEM_CLOSURE_PROOF_SOURCE_INVALID'
  | 'TEAM_SYSTEM_CLOSURE_DRIVER_PROOF_SOURCE_DUPLICATE'
  | 'TEAM_SYSTEM_CLOSURE_DRIVER_PROOF_SOURCE_INVALID'
  | 'TEAM_SYSTEM_PHASE_PROOF_SOURCE_DUPLICATE'
  | 'TEAM_SYSTEM_PHASE_PROOF_SOURCE_INVALID'
  | 'TEAM_SYSTEM_MAINTENANCE_PROOF_SOURCE_DUPLICATE'
  | 'TEAM_SYSTEM_MAINTENANCE_PROOF_SOURCE_INVALID'
  | 'TEAM_SYSTEM_INTERRUPT_PROOF_SOURCE_DUPLICATE'
  | 'TEAM_SYSTEM_INTERRUPT_PROOF_SOURCE_INVALID'
  | 'TEAM_SYSTEM_TASK_REVIEW_PROOF_SOURCE_DUPLICATE'
  | 'TEAM_SYSTEM_TASK_REVIEW_PROOF_SOURCE_INVALID'
  | 'TEAM_GOAL_STALE_REVISION'
  | 'TEAM_TASK_NOT_FOUND'
  | 'TEAM_TASK_STALE_REVISION'
  | 'TEAM_TASK_IDEMPOTENCY_CONFLICT'
  | 'TEAM_TASK_GRAPH_INVALID'
  | 'TEAM_WORKFLOW_PLAN_NOT_FOUND'
  | 'TEAM_WORKFLOW_PLAN_IDEMPOTENCY_CONFLICT'
  | 'TEAM_WORKFLOW_PLAN_STALE_REVISION'
  | 'TEAM_WORKFLOW_PLAN_INVALID'
  | 'TEAM_SYSTEM_CHANNEL_ADMISSION_PROOF_SOURCE_INVALID'
  | 'TEAM_SYSTEM_CHANNEL_ADMISSION_PROOF_SOURCE_DUPLICATE'
  | 'TEAM_CHANNEL_NOT_FOUND'
  | 'TEAM_CHANNEL_ENVELOPE_NOT_FOUND'
  | 'TEAM_CHANNEL_CURSOR_CONFLICT'
  | 'TEAM_CHANNEL_IDEMPOTENCY_CONFLICT'
  | 'TEAM_CHANNEL_BACKPRESSURE'
  | 'TEAM_CHANNEL_COMPACTED'
  | 'TEAM_AUDIT_COMPACTED'
  | 'TEAM_INBOX_COMPACTED'
  | 'TEAM_CHANNEL_ADAPTER_REJECTED'
  | 'TEAM_CLOSURE_IDEMPOTENCY_CONFLICT'
  | 'TEAM_NOT_QUIESCENT'
  | 'TEAM_CHILD_RESULT_INVALID'
  | 'TEAM_CHILD_RESULT_PARENT_PENDING'
  | 'TEAM_CHILD_RESULT_CONFLICT'
  | 'TEAM_FINAL_INVALID'
  | 'TEAM_BUDGET_INVALID'
  | 'TEAM_BUDGET_EXCEEDED'
  | 'TEAM_PARENT_USAGE_PENDING'
  | 'TEAM_GRANT_DENIED'
  | 'TEAM_DISPOSED'
  | 'TEAM_INVALID_ARGUMENT'

/** Error options that may carry JSON-safe provider details to a wire boundary. */
export interface TeamErrorOptions extends ErrorOptions {
  /** Structured details for a boundary-specific client error. */
  readonly details?: JsonObject | undefined
}

/** Error raised when a Team registry cannot honor its public contract. */
export class TeamError extends Error {
  /** Stable error classification. */
  readonly code: TeamErrorCode
  /** Optional JSON-safe details for a transport or diagnostic boundary. */
  readonly details?: JsonObject | undefined

  /**
   * @param message - human-readable rejection reason.
   * @param code - stable machine-routable error classification.
   * @param options - optional cause retained for diagnostics.
   */
  constructor(message: string, code: TeamErrorCode, options?: TeamErrorOptions) {
    super(message, options)
    this.name = 'TeamError'
    this.code = code
    this.details = options?.details
  }
}
