export { channelProtocolStatusSchema, channelHumanAdmissionSnapshotSchema } from './schema.ts'
export { channelHumanEnvelopeGetInputSchema } from './schema.ts'
/**
 * Team work-system Service Definition: independent identities, runtime record
 * parsers, channel adapters, policy waterfalls, and the abstract `ctx.teams`
 * provider contract.
 *
 * @module @clocky/clocky-team
 */

import { TeamRuntime } from './runtime.ts'

export type * from './types.ts'
export { taskHasActiveExecution, taskHasSharedWriteConflict, taskConcurrencyUsage } from './task-execution.ts'
export { teamDelegationIdSchema } from './schema.ts'
export {
  teamTaskExecutionSchema, teamTaskDelegationSnapshotSchema, teamSystemDelegationScopeSchema,
  teamTaskDelegationBeginInputSchema, teamTaskDelegationBindInputSchema, teamTaskDelegationSettleInputSchema,
  teamTaskDelegationStallInputSchema, teamChildRunAuthorizeInputSchema,
} from './schema.ts'
export { teamWorkspaceExecutionWorldSchema, teamWorkspaceLossSchema, teamWorkspaceAllocationLossInputSchema } from './schema.ts'
export type {
  TeamAdapterLease,
  TeamChannelViewEventData,
  TeamImplementationLeaseMetrics,
  TeamViewPolicyLease,
} from './types.ts'
export { TeamError } from './error.ts'
export { teamChildRunBindingSchema } from './schema.ts'
export { matchesTaskPlacement } from './placement.ts'
export { teamTaskPlacementSchema } from './schema.ts'
export type { TeamErrorCode, TeamErrorOptions } from './error.ts'
export {
  channelInvitationExpireInputSchema,
  teamSystemChannelAdmissionProofSourceNameSchema,
  teamSystemChannelAdmissionProofResolutionSchema,
  channelInvitationSnapshotSchema,
  channelInvitationIdempotencyKeySchema,
  channelManifestFingerprintSchema,
  channelInvitationAcknowledgeInputSchema,
  channelInvitationRecordSchema,
  channelAdmissionSnapshotSchema,
  channelHumanInvitationSnapshotSchema,
  teamFinalAdmissionIdempotencyKeySchema,
  teamFinalContentFingerprintSchema,
  teamFinalAdmissionInputSchema,
  teamFinalAdmissionSchema,
  activationIdSchema,
  activationBindInputSchema,
  activationBindingSnapshotSchema,
  activationFenceInputSchema,
  activationQuiesceInputSchema,
  activationQuiescenceSourceSchema,
  activationRecoverySnapshotSchema,
  activationSupervisorDescriptorSchema,
  activationGetRequestSchema,
  activationSnapshotSchema,
  activationStatusSchema,
  activationStatusUpdateInputSchema,
  channelCloseInputSchema,
  teamSystemChannelLifecycleProofResolutionSchema,
  teamSystemChannelLifecycleProofSourceNameSchema,
  teamSystemChannelLifecycleScopeSchema,
  teamSystemWorkspaceAllocationProofResolutionSchema,
  teamSystemWorkspaceAllocationProofSourceNameSchema,
  teamSystemWorkspaceAllocationScopeSchema,
  schedulerReviewChannelOpenInputSchema,
  schedulerWakeChannelOpenInputSchema,
  schedulerFailedWakeChannelCloseInputSchema,
  schedulerChannelDeliveryExpireInputSchema,
  teamCancellationChannelCloseInputSchema,
  teamFinalizationChannelCloseInputSchema,
  teamWorkflowChannelCloseInputSchema,
  channelAdapterRecordDraftSchema,
  channelAdapterRecordSchema,
  channelClosedRecordSchema,
  channelDeliveryClaimInputSchema,
  channelDeliveryClaimSchema,
  teamChannelViewEventDataSchema,
  channelDeliveryExpireResultSchema,
  channelDeliveryExpiredRecordSchema,
  channelSummarizeInputSchema,
  channelSummarySelectionInputSchema,
  channelSummaryCapabilitiesSchema,
  teamChannelCatalogSchema,
  channelSummarySourceFingerprintSchema,
  channelSummaryRecordSchema,
  channelEnvelopeRecordSchema,
  channelEnvelopePostInputSchema,
  channelFinalPostInputSchema,
  channelEnvelopeReceiptInputSchema,
  channelEventSchema,
  channelGetRequestSchema,
  channelIdSchema,
  channelManifestSchema,
  channelOpenInputSchema,
  channelPostIdempotencyKeySchema,
  channelSummaryIdempotencyKeySchema,
  channelOpenedRecordSchema,
  channelPendingDeliveryListRequestSchema,
  channelPendingDeliveryPageSchema,
  channelPendingEnvelopeDeliverySchema,
  channelPhaseRecordSchema,
  channelParticipantSchema,
  channelPhaseSchema,
  channelReadRequestSchema,
  channelReadPageRequestSchema,
  channelReadPageResultSchema,
  channelReadResultSchema,
  teamChannelCompactInputSchema,
  teamChannelCompactResultSchema,
  teamJournalCompactInputSchema,
  teamJournalCompactResultSchema,
  channelReceiptRecordSchema,
  channelRecordSchema,
  channelSnapshotSchema,
  channelWatchRequestSchema,
  channelWatchResultSchema,
  deliveryIntentSchema,
  envelopeDeliverySchema,
  envelopeIdSchema,
  envelopePrioritySchema,
  jsonObjectSchema,
  jsonValueSchema,
  teamResourceBudgetSchema,
  teamSystemActivationProofResolutionSchema,
  teamSystemActivationProofSourceNameSchema,
  teamSystemActivationScopeSchema,
  teamSystemHumanActionProofResolutionSchema,
  teamSystemHumanActionProofSourceNameSchema,
  teamSystemHumanActionScopeSchema,
  teamHumanActorPayloadFingerprintSchema,
  teamHumanActorProofFenceSchema,
  teamHumanActorProofInputSchema,
  teamHumanActorProofResolutionSchema,
  teamHumanActorProofSourceNameSchema,
  teamHumanActorScopeSchema,
  teamSystemTaskLeaseProofResolutionSchema,
  teamSystemTaskLeaseProofSourceNameSchema,
  teamSystemTaskLeaseScopeSchema,
  teamSystemWorkflowProofResolutionSchema,
  teamSystemWorkflowProofSourceNameSchema,
  teamSystemWorkflowScopeSchema,
  teamSystemTaskControlProofResolutionSchema,
  teamSystemTaskControlProofSourceNameSchema,
  teamSystemTaskControlScopeSchema,
  teamSystemRootCreationProofResolutionSchema,
  teamSystemRootCreationProofSourceNameSchema,
  teamSystemRootCreationScopeSchema,
  teamSystemChildCreationProofResolutionSchema,
  teamSystemChildCreationProofSourceNameSchema,
  teamSystemChildCreationScopeSchema,
  teamSystemChannelSummaryProofResolutionSchema,
  teamSystemChannelSummaryProofSourceNameSchema,
  teamSystemChannelSummaryScopeSchema,
  teamSystemArchiveProofResolutionSchema,
  teamSystemArchiveProofSourceNameSchema,
  teamSystemArchiveScopeSchema,
  teamSystemTopologyProofResolutionSchema,
  teamSystemTopologyProofSourceNameSchema,
  teamSystemTopologyScopeSchema,
  teamSystemSchedulerChannelProofResolutionSchema,
  teamSystemSchedulerChannelProofSourceNameSchema,
  teamSystemSchedulerChannelScopeSchema,
  teamSystemCancellationCleanupProofResolutionSchema,
  teamSystemCancellationCleanupProofSourceNameSchema,
  teamSystemCancellationCleanupScopeSchema,
  teamSystemFinalizationCleanupProofResolutionSchema,
  teamSystemFinalizationCleanupProofSourceNameSchema,
  teamSystemFinalizationCleanupScopeSchema,
  teamSystemEnvelopePostProofResolutionSchema,
  teamSystemEnvelopePostProofSourceNameSchema,
  teamSystemEnvelopePostScopeSchema,
  teamSystemClosureProofResolutionSchema,
  teamSystemClosureProofSourceNameSchema,
  teamSystemClosureScopeSchema,
  teamSystemClosureDriverProofResolutionSchema,
  teamSystemClosureDriverProofSourceNameSchema,
  teamSystemClosureDriverScopeSchema,
  teamSystemPhaseProofResolutionSchema,
  teamSystemPhaseProofSourceNameSchema,
  teamSystemPhaseScopeSchema,
  teamSystemMaintenanceProofResolutionSchema,
  teamSystemMaintenanceProofSourceNameSchema,
  teamSystemMaintenanceScopeSchema,
  teamSystemInterruptProofResolutionSchema,
  teamSystemInterruptProofSourceNameSchema,
  teamSystemInterruptScopeSchema,
  teamSystemTaskReviewProofResolutionSchema,
  teamSystemTaskReviewProofSourceNameSchema,
  teamSystemTaskReviewScopeSchema,
  teamSystemFinalReceiptProofResolutionSchema,
  teamSystemFinalReceiptProofSourceNameSchema,
  teamSystemFinalReceiptScopeSchema,
  participantInterruptAcknowledgeInputSchema,
  participantInterruptListPendingInputSchema,
  participantInterruptRequestInputSchema,
  participantInterruptSnapshotSchema,
  participantInterruptTargetSchema,
  participantIdSchema,
  participantCapabilitiesSchema,
  participantStatsSchema,
  teamTaskRankingPolicySchema,
  teamTaskExecutionStatsSchema,
  participantInviteInputSchema,
  participantKindSchema,
  participantPhaseTransitionInputSchema,
  participantPhaseSchema,
  participantSnapshotSchema,
  taskAttemptFailureSchema,
  taskAttemptIntegrationResultSchema,
  taskAttemptOutcomeSchema,
  taskAttemptResultSchema,
  teamArtifactReferenceSchema,
  teamArtifactGetRequestSchema,
  teamArtifactListPageRequestSchema,
  teamArtifactListPageSchema,
  taskAttemptSnapshotSchema,
  taskAttemptIdSchema,
  taskLeaseSnapshotSchema,
  teamAdapterRefSchema,
  teamViewPolicyRefSchema,
  teamArchiveInputSchema,
  teamResumeInputSchema,
  teamAuthorityGrantSchema,
  teamCancelInputSchema,
  teamClosureContinuationInputSchema,
  teamCreationActorSchema,
  teamClosureActorSchema,
  teamClosureInputSchema,
  teamClosureIdempotencyKeySchema,
  teamClosureKindSchema,
  teamClosureSnapshotSchema,
  teamCancellationSnapshotSchema,
  teamAuditEntrySchema,
  teamAuditReadRequestSchema,
  teamAuditReadResultSchema,
  teamAuditStreamSchema,
  teamRootCreateInputSchema,
  teamChildCreateInputSchema,
  teamCreateRequestSchema,
  teamCompleteInputSchema,
  teamEnvelopeDraftSchema,
  teamEnvelopeSchema,
  teamEventSchema,
  teamGetRequestSchema,
  teamGoalBlockerSchema,
  teamGoalPhaseSchema,
  teamGoalPhaseTransitionInputSchema,
  teamGoalSeedSchema,
  teamGoalSnapshotSchema,
  teamGoalUpdateInputSchema,
  teamHumanActionIdSchema,
  teamHumanActionSourceIdSchema,
  teamHumanActionKindSchema,
  teamHumanActionPhaseSchema,
  teamHumanActionSnapshotSchema,
  teamHumanActionUpsertInputSchema,
  teamHumanActionResolveInputSchema,
  teamUsageSampleIdSchema,
  teamUsageChargeIdSchema,
  teamTokenUsageSchema,
  teamUsageSnapshotSchema,
  teamUsageRateSchema,
  teamUsageSampleInputSchema,
  teamUsageSampleSchema,
  teamUsageChargeSchema,
  teamUsageRecordInputSchema,
  teamWorkflowConditionSchema,
  teamWorkflowGraphSchema,
  teamWorkflowPlanAdmissionInputSchema,
  teamWorkflowPlanBoundsSchema,
  teamWorkflowPlanChannelBindInputSchema,
  teamWorkflowChannelPlanSchema,
  teamWorkflowPlanGetRequestSchema,
  teamWorkflowPlanIdSchema,
  teamWorkflowPlanIdempotencyKeySchema,
  teamWorkflowPlanListPageRequestSchema,
  teamWorkflowPlanListPageSchema,
  teamWorkflowPlanPhaseInputSchema,
  teamWorkflowPlanResultSchema,
  teamWorkflowPlanSchema,
  teamWorkflowPlanSnapshotSchema,
  teamWorkflowPlanTaskBindInputSchema,
  teamWorkflowProjectedTaskResultSchema,
  teamWorkflowResultProjectionSchema,
  teamWorkflowTargetSchema,
  teamWorkflowTaskReviewPolicySchema,
  teamWorkflowTaskTemplateIdSchema,
  teamWorkflowTaskTemplateSchema,
  teamWorkflowTaskBindingSchema,
  teamWorkflowTransitionSchema,
  teamIdSchema,
  teamFailInputSchema,
  teamInterruptIdSchema,
  teamPhaseTransitionInputSchema,
  teamPhaseSchema,
  teamStallReasonSchema,
  teamPolicyDecisionSchema,
  teamPolicyHookSchema,
  teamPolicyRequestSchema,
  teamSnapshotSchema,
  teamListPageRequestSchema,
  teamListPageSchema,
  teamStateSnapshotSchema,
  teamQuiescenceSnapshotSchema,
  teamLatencyHistogramSchema,
  teamMetricsSnapshotSchema,
  teamTaskCreateInputSchema,
  teamTaskCreateCommandSchema,
  teamTaskCreateCommandInputSchema,
  teamTaskCreateIdempotencyKeySchema,
  teamTaskCommandCreatorSchema,
  teamTaskCreatorSchema,
  teamHumanTaskCreatorSchema,
  teamTaskCancelInputSchema,
  teamCancellationTaskCancelInputSchema,
  teamTaskAssignInputSchema,
  teamTaskAttemptExpireInputSchema,
  teamTaskAttemptFenceSchema,
  teamTaskAttemptHeartbeatInputSchema,
  teamTaskAttemptOwnerFenceSchema,
  teamTaskAttemptSettleInputSchema,
  teamTaskAttemptStartClaimInputSchema,
  teamTaskAttemptStartInputSchema,
  teamTaskDeleteInputSchema,
  teamTaskDetailsUpdateInputSchema,
  teamTaskOwnerProposalInputSchema,
  teamTaskGetRequestSchema,
  teamTaskIdSchema,
  teamTaskListPageRequestSchema,
  teamTaskListPageSchema,
  teamTaskPhaseSchema,
  teamTaskReviewDecisionSchema,
  teamTaskReviewPolicySchema,
  teamTaskSnapshotSchema,
  teamTaskCancellationSnapshotSchema,
  teamTaskDependencyOutcomeSchema,
  teamTaskCancellationReconcileInputSchema,
  teamTaskReviewResolveInputSchema,
  teamTaskIntegrationSpecSchema,
  teamTaskWorkspaceModeSchema,
  teamWorkspaceAllocationIdSchema,
  teamWorkspaceAllocationLifecycleSchema,
  teamWorkspaceAllocationSnapshotSchema,
  teamWorkspaceAllocationBindingInputSchema,
  teamWorkspaceAllocationReserveInputSchema,
  teamWorkspaceAllocationActivateInputSchema,
  teamWorkspaceAllocationReleaseRequestInputSchema,
  teamWorkspaceAllocationPreserveInputSchema,
  teamWorkspaceAllocationReleaseInputSchema,
  teamMemberListPageRequestSchema,
  teamMemberListPageSchema,
  teamChannelListInputSchema,
  teamChannelListPageSchema,
  teamWatchRequestSchema,
  teamWatchResultSchema,
} from './schema.ts'
export {
  assertActivationStatusTransition,
  assertChannelPhaseTransition,
  assertParticipantPhaseTransition,
  assertTeamGoalPhaseTransition,
  assertTeamPhaseTransition,
  assertTeamTaskPhaseTransition,
} from './lifecycle.ts'
export { TeamRuntime }
export { fingerprintTeamHumanActorPayload, fingerprintTeamFinalContent, fingerprintChannelSummarySources, channelSummaryHumanProofInput, fingerprintChannelManifest } from './human-actor.ts'
export { validateTeamWorkflowPlan } from './workflow.ts'
export {
  TEAM_LATENCY_BUCKETS_MS,
  addTeamLatencySample,
  emptyTeamLatencyHistogram,
} from './metrics.ts'
export {
  TeamTelemetryCoordinator,
  TeamTelemetryBackend,
} from './telemetry.ts'
export type {
  TeamTelemetryRecord,
  TeamTelemetrySeverity,
  TeamTelemetrySink,
} from './telemetry.ts'

export default TeamRuntime

export { teamWorkspaceObservationIdSchema, teamWorkspaceContentVersionSchema, teamWorkspaceScanVersionSchema,
  teamWorkspaceObservationInputSchema, teamWorkspaceObservationSchema } from './schema.ts'

export { teamHumanInboxReadInputSchema, teamHumanInboxAcknowledgeInputSchema, teamHumanFinalInputSchema, teamHumanInboxItemSchema, teamHumanInboxPageSchema, teamHumanInboxAcknowledgementSchema } from './schema.ts'

export { teamHumanInboxFinalSchema, teamHumanMessageInputSchema, teamHumanInboxMessageSchema, teamSystemHumanDeliveryScopeSchema } from './schema.ts'

export { teamHumanInboxActionSchema, teamHumanActionResponseInputSchema, teamHumanActionResponseIdempotencyKeySchema, teamHumanActionResponseResultSchema } from './schema.ts'

export { teamChildResultFingerprintSchema, teamDelegationResultAdmissionSchema, teamChildResultAdmissionSchema, teamTaskDelegationResultAdmitInputSchema, teamSystemChildResultScopeSchema, teamChildResultCommandInputSchema, teamChildCancelInputSchema } from './schema.ts'
export { fingerprintTeamChildResultContent } from './human-actor.ts'
